mpi:
  - nompi
  - mpich  # [not (osx and arm64)]
  - openmpi  # [not (osx and arm64)]
pin_run_as_build:
  mpich: x.x
  openmpi: x.x 
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk   # [osx]
libblas:
- 3.8 *netlib
liblapack:
- 3.8.0 *netlib
