name: CI

on:
  push:
  pull_request:

env:
# on CI, better dump stack trace in case there is an error
  PLUMED_STACK_TRACE: yes
# use two threads for openMP tests
  PLUMED_NUM_THREADS: 2
# these are used to build required packages
  CC: gcc
  CXX: g++

jobs:
  fedora34:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests
      run: |
        make -C docker fedora34

